version: '3.7'
services:
  metastore_db:
    image: postgres:10.5
    hostname: metastore
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${HMS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HMS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HMS_POSTGRES_DB}
      POSTGRES_PORT: ${HMS_POSTGRES_PORT}
      POSTGRES_HOST: ${HMS_POSTGRES_HOST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metastore" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
        - ml_platform

  hive_metastore:
    hostname: hive_metastore
    build:
      context: ./hivemetastore
    depends_on:
      metastore_db:
        condition: service_healthy
    ports:
      - "9083:9083"
    environment:
      METASTORE_DB_DB: ${HMS_POSTGRES_DB}
      METASTORE_DB_HOST: ${HMS_POSTGRES_HOST}
      METASTORE_DB_PORT: ${HMS_POSTGRES_PORT}
      METASTORE_DB_USER: ${HMS_POSTGRES_USER}
      METASTORE_DB_PASS: ${HMS_POSTGRES_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    healthcheck:
      test: netstat -ltn | grep -c 9083
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      ml_platform:
        ipv4_address: ${HIVE_METASTORE_ADDRESS}

  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - /mnt/38390e7f-c8b3-4b79-8750-eff41b386f03/ml_platform_data:/data 
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    hostname: minio
    entrypoint: sh
    command: -c 'mkdir -p /data/storage && /usr/bin/minio server /data'  
    networks: 
      - ml_platform

  spark-master:
    hostname: spark-master
    image: datadrone/spark-master:3.1.1-hadoop3.2-rapids
    ports:
      - "9080:8080"
      - "7077:7077"
    links:
      - hive_metastore
    environment:
      SPARK_LOCAL_IP: "spark-master"
      PYSPARK_PYTHON: /usr/bin/python3
      PYSPARK_DRIVER_PYTHON: /usr/bin/python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      hive_metastore:
        condition: service_healthy
    networks: 
      - ml_platform

  spark-worker-1:
    image: datadrone/spark-worker:3.1.1-hadoop3.2-rapids
    depends_on:
      - spark-master
    ports:
      - "4040:4040"
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_WORKER_CORES: 16
      SPARK_WORKER_MEMORY: 32G
      SPARK_DRIVER_MEMORY: 128m
      SPARK_EXECUTOR_MEMORY: 256m
      SPARK_WORKER_OPTS: -Dspark.worker.resource.gpu.amount=2 -Dspark.worker.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh
      PYSPARK_PYTHON: /usr/bin/python3
      PYSPARK_DRIVER_PYTHON: /usr/bin/python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu, utility, compute]
    links:
        - hive_metastore
    networks:
      - ml_platform

  spark-thrift-server:
    build:
      context: ./spark_thrift_server
    ports:
      - "10000:10000"
    depends_on:
      hive_metastore:
        condition: service_healthy
    environment:
      JAVA_HOME: /usr
      SPARK_MASTER: spark://spark-master:7077
      PYSPARK_PYTHON: /usr/bin/python3
      PYSPARK_DRIVER_PYTHON: /usr/bin/python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      SPARK_APPLICATION_MAIN_CLASS: org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      HIVE_METASTORE_ADDRESS: ${HIVE_METASTORE_ADDRESS}
    networks:
      - ml_platform

  spark-notebook:
    image: datadrone/spark_notebook:3.1.1-hadoop3.2
    ports:
      - "9494:8888"
    volumes:
      - ./dev_notebooks:/home/jovyan/work/dev_notebooks
      - ../projects:/home/jovyan/work/projects
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JAVA_HOME: /usr
      SPARK_MASTER: "spark://spark-master:7077"
      PYSPARK_PYTHON: /usr/bin/python3
      PYSPARK_DRIVER_PYTHON: /usr/bin/python3
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ipc: host  
    links:
        - hive_metastore
    networks:
      - ml_platform

networks:
  ml_platform:
    driver: bridge
    external: true
    #ipam:
    #  config:
    #    - subnet: 172.30.0.0/16